# SPDX-FileCopyrightText: 2021 Nextcloud GmbH and Nextcloud contributors
# SPDX-License-Identifier: AGPL-3.0-or-later
version: 2
updates:
- package-ecosystem: composer
  directories:
    - "/"
    - "/vendor-bin/csfixer"
    - "/vendor-bin/psalm"
  commit-message:
    prefix: "ci"
    include: "scope"
  versioning-strategy: "increase"
  schedule:
    interval: weekly
    day: saturday
    time: "03:00"
    timezone: Europe/Berlin
  open-pull-requests-limit: 10
  labels:
    - 3. to review
    - dependencies
  cooldown:
    default-days: 4

- package-ecosystem: npm
  directory: "/"
  commit-message:
    prefix: "build"
    include: "scope"
  versioning-strategy: "increase"
  schedule:
    interval: weekly
    day: saturday
    time: "03:00"
    timezone: Europe/Berlin
  open-pull-requests-limit: 10
  labels:
    - 3. to review
    - dependencies
  cooldown:
    default-days: 4
    exclude:
      - "@nextcloud/*"

- package-ecosystem: npm
  target-branch: stable33
  directory: "/"
  commit-message:
    prefix: "build"
    include: "scope"
  versioning-strategy: "increase"
  schedule:
    interval: weekly
    day: saturday
    time: "03:00"
    timezone: Europe/Berlin
  open-pull-requests-limit: 10
  labels:
    - 3. to review
    - dependencies
  ignore:
    - dependency-name: "*"
      update-types: ["version-update:semver-major", "version-update:semver-minor"]
  cooldown:
    default-days: 4
    exclude:
      - "@nextcloud/*"

- package-ecosystem: npm
  target-branch: stable32
  directory: "/"
  commit-message:
    prefix: "build"
    include: "scope"
  versioning-strategy: "increase"
  schedule:
    interval: weekly
    day: saturday
    time: "03:00"
    timezone: Europe/Berlin
  open-pull-requests-limit: 10
  labels:
    - 3. to review
    - dependencies
  ignore:
    - dependency-name: "*"
      update-types: ["version-update:semver-major", "version-update:semver-minor"]
  cooldown:
    default-days: 4
    exclude:
      - "@nextcloud/*"

- package-ecosystem: npm
  target-branch: stable31
  directory: "/"
  commit-message:
    prefix: "build"
    include: "scope"
  versioning-strategy: "increase"
  schedule:
    interval: weekly
    day: saturday
    time: "03:00"
    timezone: Europe/Berlin
  open-pull-requests-limit: 10
  labels:
    - 3. to review
    - dependencies
  ignore:
    - dependency-name: "*"
      update-types: ["version-update:semver-major", "version-update:semver-minor"]
  cooldown:
    default-days: 4
    exclude:
      - "@nextcloud/*"

